[package]
name = "code_chef_6"
version = "0.1.0"
authors = ["Amna <amnakhan8685@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
